services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - catchwise-esg-app-network
    healthcheck:
      test: "mongo --eval 'db.runCommand({ ping: 1 })'"
      interval: 10s
      timeout: 5s
      retries: 5
      
  catchwise-esg-app:
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
    container_name: catchwise-esg-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongodb:27017/ESG
    networks:
      - catchwise-esg-app-network
    depends_on:
      - mongodb

  nginx:
    build:
      context: .
      dockerfile: Dockerfile
      target: nginx
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - catchwise-esg-app-network
    depends_on:
      - catchwise-esg-app

volumes:
  mongo_data:

networks:
  catchwise-esg-app-network:
    driver: bridge